# {
#   "Elevation axis in stow position": false,
#   "Elevation stow pins - status": 0,
#   "AT Lock On": false,
# }

status_fields = {
    'latp' : {
        'status_fields':   {
            'summary':    {
                'Time': 'Time',
                'Year': 'Year',
                'Azimuth Mode': 'Azimuth_mode',
                'Azimuth current position': 'Azimuth_current_position',
                'Azimuth current velocity': 'Azimuth_current_velocity',
                'Elevation Mode': 'Elevation_mode',
                'Elevation current position': 'Elevation_current_position',
                'Elevation current velocity': 'Elevation_current_velocity',
                'Qty of free program track stack positions': 'Free_upload_positions',
                "Elevation axis in stow position": 'Elevation_axis_in_stow_position',
                "Elevation stow pins - status": 'Elevation_stow_pins_status',
                "AT Lock On": 'AT_Lock_On',
                },
            'position_errors':    {
                'Azimuth average position error': 'Azimuth_avg_position_error',
                'Azimuth peak position error': 'Azimuth_peak_position_error',
                'Elevation average position error': 'Elevation_avg_position_error',
                'Elevation peak position error': 'Elevation_peak_position_error',
                },
            'axis_limits':    {
            #     'Azimuth CCW limit: 2nd emergency': 'AzCCW_HWlimit_2ndEmergency',
            #     'Azimuth CCW limit: emergency': 'AzCCW_HWlimit_emergency',
            #     'Azimuth CCW limit: operating': 'AzCCW_HWlimit_operating',
            #     'Azimuth CCW limit: pre-limit': 'AzCCW_HWprelimit',
                'Azimuth CCW limit': 'AzCCW_SWlimit_operating',
            #     'Azimuth CCW limit: pre-limit (ACU software limit)': 'AzCCW_SWprelimit',
            #     'Azimuth CW limit: pre-limit (ACU software limit)': 'AzCW_SWprelimit',
                'Azimuth CW limit': 'AzCW_SWlimit_operating',
            #     'Azimuth CW limit: pre-limit': 'AzCW_HWprelimit',
            #     'Azimuth CW limit: operating': 'AzCW_HWlimit_operating',
            #     'Azimuth CW limit: emergency': 'AzCW_HWlimit_emergency',
            #     'Azimuth CW limit: 2nd emergency': 'AzCW_HWlimit_2ndEmergency',
            #     'Elevation Down limit: emergency': 'ElDown_HWlimit_emergency',
            #     'Elevation Down limit: operating': 'ElDown_HWlimit_operating',
            #     'Elevation Down limit: pre-limit': 'ElDown_HWprelimit',
                'Elevation CCW limit': 'ElDown_SWlimit_operating',
            #     'Elevation Down limit: pre-limit (ACU software limit)': 'ElDown_SWprelimit',
            #     'Elevation Up limit: pre-limit (ACU software limit)': 'ElUp_SWprelimit',
                'Elevation CW limit': 'ElUp_SWlimit_operating',
            #     'Elevation Up limit: pre-limit': 'ElUp_HWprelimit',
            #     'Elevation Up limit: operating': 'ElUp_HWlimit_operating',
            #     'Elevation Up limit: emergency': 'ElUp_HWlimit_emergency',
                },
            'axis_faults_errors_overages':    {
                'Azimuth summary fault': 'Azimuth_summary_fault',
            #     'Azimuth motion error': 'Azimuth_motion_error',
            #     'Azimuth motor 1 overtemperature': 'Azimuth_motor1_overtemp',
            #     'Azimuth motor 2 overtemperature': 'Azimuth_motor2_overtemp',
            #     'Azimuth overspeed': 'Azimuth_overspeed',
            #     'Azimuth regeneration resistor 1 overtemperature': 'Azimuth_resistor1_overtemp',
            #     'Azimuth regeneration resistor 2 overtemperature': 'Azimuth_resistor2_overtemp',
            #     'Azimuth overcurrent motor 1': 'Azimuth_motor1_overcurrent',
            #     'Azimuth overcurrent motor 2': 'Azimuth_motor2_overcurrent',
                'Elevation summary fault': 'Elevation_summary_fault',
            #     'Elevation motion error': 'Elevation_motion_error',
            #     'Elevation motor 1 overtemp': 'Elevation_motor1_overtemp',
            #     'Elevation overspeed': 'Elevation_overspeed',
            #     'Elevation regeneration resistor 1 overtemperature': 'Elevation_resistor1_overtemp',
            #     'Elevation overcurrent motor 1': 'Elevation_motor1_overcurrent',
                },
            # 'axis_warnings':    {
            #     'Azimuth oscillation warning': 'Azimuth_oscillation_warning',
            #     'Elevation oscillation warning': 'Elevation_oscillation_warning',
            #     },
            # 'axis_failures':    {
            #     'Azimuth servo failure': 'Azimuth_servo_failure',
            #     'Azimuth brake 1 failure': 'Azimuth_brake1_failure',
            #     'Azimuth brake 2 failure': 'Azimuth_brake2_failure',
            #     'Azimuth breaker failure': 'Azimuth_breaker_failure',
            #     'Azimuth amplifier power cylce interlock': 'Azimuth_power_cycle_interlock',
            #     'Azimuth amplifier 1 failure': 'Azimuth_amp1_failure',
            #     'Azimuth amplifier 2 failure': 'Azimuth_amp2_failure',
            #     'Azimuth CAN bus amplifier 1 communication failure': 'Az_CANbus_amp1_comms_failure',
            #     'Azimuth CAN bus amplifier 2 communication failure': 'Az_CANbus_amp2_comms_failure',
            #     'Azimuth encoder failure': 'Azimuth_encoder_failure',
            #     'Azimuth tacho failure': 'Azimuth_tacho_failure',
            #     'Elevation servo failure': 'Elevation_servo_failure',
            #     'Elevation brake 1 failure': 'Elevation_brake1_failure',
            #     'Elevation breaker failure': 'Elevation_breaker_failure',
            #     'Elevation amplifier power cylce interlock': 'Elevation_power_cycle_interlock',
            #     'Elevation amplifier 1 failure': 'Elevation_amp1_failure',
            #     'Elevation CAN bus amplifier 1 communication failure': 'El_CANbus_amp1_comms_failure',
            #     'Elevation encoder failure': 'Elevation_encoder_failure',
            #     },
            'axis_state':    {
                'Azimuth computer disabled': 'Azimuth_computer_disabled',
                'Azimuth axis disabled': 'Azimuth_disabled',
                'Azimuth axis in stop': 'Azimuth_axis_stop',
                'Azimuth brakes released': 'Azimuth_brakes_released',
                'Azimuth stop at LCP': 'Azimuth_stop_LCP',
                'Azimuth power on': 'Azimuth_power_on',
            #     'Azimuth AUX 1 mode selected': 'Azimuth_AUX1_mode_selected',
            #     'Azimuth AUX 2 mode selected': 'Azimuth_AUX2_mode_selected',
            #     'Azimuth immobile': 'Azimuth_immobile',
                'Elevation computer disabled': 'Elevation_computer_disabled',
                'Elevation axis disabled': 'Elevation_disabled',
                'Elevation axis in stop': 'Elevation_axis_stop',
                'Elevation brakes released': 'Elevation_brakes_released',
                'Elevation stop at LCP': 'Elevation_stop_LCP',
                'Elevation power on': 'Elevation_power_on',
            #     'Elevation immobile': 'Elevation_immobile',
                },
            # 'osc_alarms':    {
            #     'Azimuth oscillation alarm': 'Azimuth_oscillation_alarm',
            #     'Elevation oscillation alarm': 'Elevation_oscillation_alarm',
            #     },
            'commands':    {
                'Azimuth commanded position': 'Azimuth_commanded_position',
                'Elevation commanded position':  'Elevation_commanded_position',
                },
            # 'ACU_failures_errors':    {
            #     'General summary fault': 'General_summary_fault',
            #     'Power failure (latched)': 'Power_failure_Latched',
            #     '24V power failure': 'Power_failure_24V',
            #     'General Breaker failure': 'General_breaker_failure',
            #     'Power failure (not latched)': 'Power_failure_NotLatched',
            #     'Cabinet Overtemperature': 'Cabinet_overtemp',
            #     'Ambient temperature low (operation inhibited)': 'Ambient_temp_TooLow',
            #     'PLC-ACU interface error': 'PLC_interface_error',
            #     'ACU fan failure': 'ACU_fan_failure',
            #     'Cabinet undertemperature': 'Cabinet_undertemp',
            #     'Time synchronisation error': 'Time_sync_error',
            #     'ACU-PLC communication error': 'PLC_comms_error',
            #     'Program Track position failure': 'ProgramTrack_position_failure',
            #     'Start of Program Track too early': 'Track_start_too_early',
            #     'Turnaround acceleration too high': 'Turnaround_accel_too_high',
            #     'Turnaround time too short': 'Turnaround_time_too_short',
            #     },
            'platform_status':    {
                'PCU Operation': 'PCU_operation',
            #     'Safe': 'Safe_mode',
            #     'Lightning protection surge arresters': 'Lightning_protection_surge_arresters',
            #     'Co-Moving Shield off': 'CoMoving_shield_off',
                'Remote': 'Remote_mode',
                },
            # 'ACU_emergency':    {
            #     'E-Stop servo drive cabinet': 'EStop_servo_drive_cabinet',
            #     'E-Stop service pole': 'EStop_service_pole',
            #     'E-Stop Az movable': 'EStop_Az_movable',
            #     'Key Switch Bypass Emergency Limit': 'Key_switch_bypass_emergency_limit',
            #     }
            }
        },

    }

def allkeys(platform_type):
    all_keys = []
    pfd = status_fields[platform_type]['status_fields']
    for category in pfd.keys():
        for key in pfd[category].keys():
            all_keys.append(key)
    return all_keys