status_fields = {
    'latp' : {
        'status_fields':   {
            'summary':    {
                'Time': 'Time',
                'Year': 'Year',
                'Azimuth mode': 'Azimuth_mode',
                'Azimuth current position': 'Azimuth_current_position',
                'Azimuth current velocity': 'Azimuth_current_velocity',
                'Elevation mode': 'Elevation_mode',
                'Elevation current position': 'Elevation_current_position',
                'Elevation current velocity': 'Elevation_current_velocity',
                'Qty of free program track stack positions': 'Free_upload_positions',
                'Elevation Stowpin Status': 'Elevation_stowpin_status',
                'Elevation Stowpin Failure': 'Elevation_stowpin_failure',
                },
            'position_errors':    {
                'Azimuth average position error': 'Azimuth_avg_position_error',
                'Azimuth peak position error': 'Azimuth_peak_position_error',
                'Elevation average position error': 'Elevation_avg_position_error',
                'Elevation peak position error': 'Elevation_peak_position_error',
                },
            'axis_limits':    {
                'Azimuth CCW limit: 2nd emergency':                    'AzCCW_HWlimit_2ndEmergency',
                'Azimuth CCW limit: emergency':                        'AzCCW_HWlimit_emergency',
                'Azimuth CCW limit: operating':                        'AzCCW_HWlimit_operating',
                'Azimuth CCW limit: pre-limit':                        'AzCCW_HWprelimit',
                'Azimuth CCW limit: operating (ACU software limit)':   'AzCCW_SWlimit_operating',
                'Azimuth CCW limit: pre-limit (ACU software limit)':   'AzCCW_SWprelimit',
                'Azimuth CW limit: pre-limit (ACU software limit)':    'AzCW_SWprelimit',
                'Azimuth CW limit: operating (ACU software limit)':    'AzCW_SWlimit_operating',
                'Azimuth CW limit: pre-limit':                         'AzCW_HWprelimit',
                'Azimuth CW limit: operating':                         'AzCW_HWlimit_operating',
                'Azimuth CW limit: emergency':                         'AzCW_HWlimit_emergency',
                'Azimuth CW limit: 2nd emergency':                     'AzCW_HWlimit_2ndEmergency',
                'Elevation Down limit: 2nd emergency':                 'ElDown_HWlimit_2ndEmergency',
                'Elevation Down limit: emergency':                     'ElDown_HWlimit_emergency',
                'Elevation Down limit: operating':                     'ElDown_HWlimit_operating',
                'Elevation Down limit: pre-limit':                     'ElDown_HWprelimit',
                'Elevation Down limit: operating (ACU software limit)':'ElDown_SWlimit_operating',
                'Elevation Down limit: pre-limit (ACU software limit)':'ElDown_SWprelimit',
                'Elevation Up limit: pre-limit (ACU software limit)':  'ElUp_SWprelimit',
                'Elevation Up limit: operating (ACU software limit)':  'ElUp_SWlimit_operating',
                'Elevation Up limit: pre-limit':                       'ElUp_HWprelimit',
                'Elevation Up limit: operating':                       'ElUp_HWlimit_operating',
                'Elevation Up limit: emergency':                       'ElUp_HWlimit_emergency',
                'Elevation Up limit: 2nd emergency':                   'ElUp_HWlimit_2ndEmergency',
                },
            'axis_faults_errors_overages':    {
                'Azimuth summary fault': 'Azimuth_summary_fault',
                'Elevation summary fault': 'Elevation_summary_fault',
                },
            'axis_state':    {
                'Azimuth computer disabled': 'Azimuth_computer_disabled',
                'Azimuth axis disabled': 'Azimuth_disabled',
                'Azimuth axis in stop': 'Azimuth_axis_stop',
                'Azimuth brakes released': 'Azimuth_brakes_released',
                'Azimuth stop at LCP': 'Azimuth_stop_LCP',
                'Azimuth power on': 'Azimuth_power_on',
                'Elevation computer disabled': 'Elevation_computer_disabled',
                'Elevation axis disabled': 'Elevation_disabled',
                'Elevation axis in stop': 'Elevation_axis_stop',
                'Elevation brakes released': 'Elevation_brakes_released',
                'Elevation stop at LCP': 'Elevation_stop_LCP',
                'Elevation power on': 'Elevation_power_on',
                },
            'commands':    {
                'Azimuth commanded position': 'Azimuth_commanded_position',
                'Elevation commanded position':  'Elevation_commanded_position',
                },
            'platform_status':    {
                'PCU operation': 'PCU_operation',
                'ACU in remote mode': 'Remote_mode',
                'General summary fault': 'General_summary_fault',
                'Sun avoidance Interlock has triggered': 'Sun_avoidance_interlock_triggered',
                'Sun Interlock - antenna cannot move': 'Sun_interlock_antenna_cannot_move',
                },
            'sun_avoidance':    {
                'Sun avoidance Interlock enabled': 'Sun_avoidance_interlock_enabled',
                'Sun avoidance Interlock has triggered': 'Sun_avoidance_interlock_triggered',
                'Antenna moving due to sun Interlock': 'Antenna_moving_due_to_sun',
                'Sun Interlock - antenna cannot move': 'Sun_interlock_antenna_cannot_move',
                'Minimum distance to sun': 'Min_distance_to_sun',
                'Minimum velocity to cross sun': 'Min_velocity_to_cross_sun',
                'Distance to Sun': 'Distance_to_Sun',
                },
            'faults':    {
                'Az - Encoder Failure': 'Az_encoder_failure',
                'Az - Tacho Failure': 'Az_tacho_failure',
                'Az - ACU immobile': 'Az_immobile',
                'Az - Servo Failure': 'Az_servo_failure',
                'Az - Motion Error': 'Az_motion_error',
                'Az - Brake1 Failure': 'Az_brake1_failure',
                'Az - Brake2 Failure': 'Az_brake2_failure',
                'Az - Brake3 Failure': 'Az_brake3_failure',
                'Az - Brake4 Failure': 'Az_brake4_failure',
                'Az - Breaker Failure': 'Az_breaker_failure',
                'Az - Amplifier1 Failure': 'Az_amp1_failure',
                'Az - Amplifier2 Failure': 'Az_amp2_failure',
                'Az - Amplifier3 Failure': 'Az_amp3_failure',
                'Az - Amplifier4 Failure': 'Az_amp4_failure',
                'Az - Motor1 OverTemp': 'Az_motor1_overtemp',
                'Az - Motor2 OverTemp': 'Az_motor2_overtemp',
                'Az - Motor3 OverTemp': 'Az_motor3_overtemp',
                'Az - Motor4 OverTemp': 'Az_motor4_overtemp',
                'Az - Overspeed': 'Az_overspeed',
                'El - Encoder Failure': 'El_encoder_failure',
                'El - Tacho Failure': 'El_tacho_failure',
                'El - ACU immobile': 'El_immobile',
                'El - Servo Failure': 'El_servo_failure',
                'El - Motion Error': 'El_motion_error',
                'El - Brake1 Failure': 'El_brake1_failure',
                'El - Brake2 Failure': 'El_brake2_failure',
                'El - Breaker Failure': 'El_breaker_failure',
                'El - Amplifier1 Failure': 'El_amp1_failure',
                'El - Amplifier2 Failure': 'El_amp2_failure',
                'El - Motor1 OverTemp': 'El_motor1_overtemp',
                'El - Motor2 OverTemp': 'El_motor2_overtemp',
                'El - Overspeed': 'El_overspeed',
                'General ACU fan failure': 'ACU_fan_failure',
                'General ACU over temperature': 'ACU_over_temperature',
                'General Time Error': 'ACU_time_error',
                },
            'shutter':    {
                'Shutter Closed':   'Shutter_closed',
                'Shutter Moving':   'Shutter_moving',
                'Shutter Open':     'Shutter_open',
                'Shutter Timeout':  'Shutter_timeout',
                'Shutter Failure':  'Shutter_failure',
                'Move Interlock':   'Move_interlock',
                'Distance to Sun':  'Distance_to_Sun',
                },
            'hvac':    {
                'Temperature EL Housing 1':                              'Temp_EL_housing_1',
                'Temperature EL Housing 2':                              'Temp_EL_housing_2',
                'Temperature EL Housing 3':                              'Temp_EL_housing_3',
                'Temperature EL Housing 4':                              'Temp_EL_housing_4',
                'Temperature EL Housing 5':                              'Temp_EL_housing_5',
                'Temperature EL Housing 6':                              'Temp_EL_housing_6',
                'Temperature Yoke Arm B 1':                              'Temp_yoke_arm_B_1',
                'Temperature Yoke Arm B 2':                              'Temp_yoke_arm_B_2',
                'Temperature Yoke Arm B 3':                              'Temp_yoke_arm_B_3',
                'Temperature Yoke Arm B 4':                              'Temp_yoke_arm_B_4',
                'Temperature Yoke Arm A Instrument Space 1':             'Temp_yoke_arm_A_inst_1',
                'Temperature Yoke Arm A Instrument Space 2':             'Temp_yoke_arm_A_inst_2',
                'Temperature Yoke Arm A Instrument Space 3':             'Temp_yoke_arm_A_inst_3',
                'Temperature Yoke Arm A Instrument Space 4':             'Temp_yoke_arm_A_inst_4',
                'Temperature Yoke Arm A Instrument Space 5':             'Temp_yoke_arm_A_inst_5',
                'Temperature Yoke Arm A Instrument Space 6':             'Temp_yoke_arm_A_inst_6',
                'Temperature Yoke Traverse B Process Space 1':           'Temp_yoke_trav_B_proc_1',
                'Temperature Yoke Traverse B Process Space 2':           'Temp_yoke_trav_B_proc_2',
                'Temperature Yoke Traverse B Process Space 3':           'Temp_yoke_trav_B_proc_3',
                'Temperature Yoke Traverse B Process Space 4':           'Temp_yoke_trav_B_proc_4',
                'Temperature Yoke Traverse M Servo Space 1':             'Temp_yoke_trav_M_servo_1',
                'Temperature Yoke Traverse M Servo Space 2':             'Temp_yoke_trav_M_servo_2',
                'Temperature Yoke Traverse M Servo Space 3':             'Temp_yoke_trav_M_servo_3',
                'Temperature Yoke Traverse M Servo Space 4':             'Temp_yoke_trav_M_servo_4',
                'Temperature Yoke Traverse A Electronic Space 1':        'Temp_yoke_trav_A_elec_1',
                'Temperature Yoke Traverse A Electronic Space 2':        'Temp_yoke_trav_A_elec_2',
                'Temperature Yoke Traverse A Electronic Space 3':        'Temp_yoke_trav_A_elec_3',
                'Temperature Yoke Traverse A Electronic Space 4':        'Temp_yoke_trav_A_elec_4',
                'Temperature MPD Container 1':                           'Temp_MPD_container_1',
                'Temperature MPD Container 2':                           'Temp_MPD_container_2',
                'Temperature Ambient 1':                                 'Temp_ambient_1',
                'Temperature Ambient 2':                                 'Temp_ambient_2',
                'Temperature Average EL Housing':                        'Temp_avg_EL_housing',
                'Temperature Average Yoke Arm B':                        'Temp_avg_yoke_arm_B',
                'Temperature Average Yoke Arm A Instrument Space':       'Temp_avg_yoke_arm_A_inst',
                'Temperature Average Yoke Traverse B Process Space':     'Temp_avg_yoke_trav_B_proc',
                'Temperature Average Yoke Traverse M Servo Space':       'Temp_avg_yoke_trav_M_servo',
                'Temperature Average Yoke Traverse A Electronic Space':  'Temp_avg_yoke_trav_A_elec',
                'Temperature Average MPD Container':                     'Temp_avg_MPD_container',
                'Temperature Average Ambient':                           'Temp_avg_ambient',
                'Setpoint Temperature Yoke Traverse':                    'Setpoint_temp_yoke_traverse',
                'Setpoint Speed Fan Yoke Arm B':                         'Setpoint_fan_yoke_arm_B',
                'Setpoint Speed Fan Yoke Arm A Instrument Space':        'Setpoint_fan_yoke_arm_A_inst',
                'Setpoint Speed Fan Yoke Traverse B Process Space':      'Setpoint_fan_yoke_trav_B_proc',
                'Setpoint Speed Fan Yoke Traverse M Servo Space':        'Setpoint_fan_yoke_trav_M_servo',
                'Setpoint Speed Fan Yoke Traverse A Electronic Space':   'Setpoint_fan_yoke_trav_A_elec',
                'Booster EL Housing Failure':                            'Booster_EL_housing_failure',
                'Booster Yoke Traverse B Process Space Failure':         'Booster_yoke_trav_B_proc_failure',
                'Booster Yoke Traverse M Servo Space Failure':           'Booster_yoke_trav_M_servo_failure',
                'Booster Yoke Traverse A Electronic Space Failure':      'Booster_yoke_trav_A_elec_failure',
                'Fan EL Housing Failure':                                'Fan_EL_housing_failure',
                'Fan Yoke Arm B Failure':                                'Fan_yoke_arm_B_failure',
                'Fan Yoke Arm A Instrument Space Failure':               'Fan_yoke_arm_A_inst_failure',
                'Fan Yoke Traverse B Process Space Failure':             'Fan_yoke_trav_B_proc_failure',
                'Fan Yoke Traverse M Servo Space Failure':               'Fan_yoke_trav_M_servo_failure',
                'Fan Yoke Traverse A Electronic Space Failure':          'Fan_yoke_trav_A_elec_failure',
                'Booster EL Housing on':                                 'Booster_EL_housing_on',
                'Booster Yoke Traverse B Process Space on':              'Booster_yoke_trav_B_proc_on',
                'Booster Yoke Traverse M Servo Space on':                'Booster_yoke_trav_M_servo_on',
                'Booster Yoke Traverse A Electronic Space on':           'Booster_yoke_trav_A_elec_on',
                'Fan EL Housing on':                                     'Fan_EL_housing_on',
                'Fan Yoke Arm B on':                                     'Fan_yoke_arm_B_on',
                'Fan Yoke Arm A Instrument Space on':                    'Fan_yoke_arm_A_inst_on',
                'Fan Yoke Traverse B Process Space on':                  'Fan_yoke_trav_B_proc_on',
                'Fan Yoke Traverse M Servo Space on':                    'Fan_yoke_trav_M_servo_on',
                'Fan Yoke Traverse A Electronic Space on':               'Fan_yoke_trav_A_elec_on',
                'Heater on':                                             'Heater_on',
                },
            'corrections':    {
                'Systematic error model (SPEM) on': 'SPEM_on',
                'Tiltmeter Az correction on': 'Tiltmeter_Az_correction_on',
                'Tiltmeter El correction on': 'Tiltmeter_El_correction_on',
                'RF refraction correction on': 'RF_refraction_correction_on',
                'SPEM correction AZ': 'SPEM_correction_AZ',
                'SPEM correction EL': 'SPEM_correction_EL',
                'Tiltmeter Az correction AZ': 'Tiltmeter_Az_correction_AZ',
                'Tiltmeter Az correction EL': 'Tiltmeter_Az_correction_EL',
                'Tiltmeter El correction AZ': 'Tiltmeter_El_correction_AZ',
                'Tiltmeter El correction EL': 'Tiltmeter_El_correction_EL',
                'RF refraction correction AZ': 'RF_refraction_correction_AZ',
                'RF refraction correction EL': 'RF_refraction_correction_EL',
                },
            }
        },

    }

def allkeys(platform_type):
    all_keys = []
    pfd = status_fields[platform_type]['status_fields']
    for category in pfd.keys():
        for key in pfd[category].keys():
            all_keys.append(key)
    return all_keys